# Generated by Django 2.1.7 on 2019-02-27 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('instagram_name', models.CharField(blank=True, max_length=200)),
                ('twitter_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('team_name', models.CharField(max_length=200)),
                ('made_playoffs', models.BooleanField()),
                ('playoff_wins', models.IntegerField()),
                ('playoff_losses', models.IntegerField()),
                ('made_superbowl', models.BooleanField()),
                ('superbowl_wins', models.IntegerField()),
                ('superbowl_losses', models.IntegerField()),
                ('acquisitions', models.IntegerField()),
                ('trades', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.Owner')),
            ],
        ),
    ]
